-- ========================================================
-- DATABASE INITIALIZATION SCRIPT (PostgreSQL)
-- Application: Notes App (React + Express)
-- ========================================================

-- 1. TRIGGER FUNCTIONS (Automatic updated_at timestamps)

CREATE OR REPLACE FUNCTION public.update_timestamp() 
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_user_timestamp() 
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- 2. USERS TABLE

CREATE TABLE IF NOT EXISTS public.users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(100) NOT NULL UNIQUE,
    password character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- 3. NOTES TABLE

CREATE TABLE IF NOT EXISTS public.notes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_user integer NOT NULL,
    title character varying(255),
    text text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT notes_pkey PRIMARY KEY (id),
    CONSTRAINT notes_id_user_fkey FOREIGN KEY (id_user) 
        REFERENCES public.users(id) ON DELETE CASCADE
);

-- 4. TRIGGERS

DROP TRIGGER IF EXISTS set_user_timestamp ON public.users;
CREATE TRIGGER set_user_timestamp 
    BEFORE UPDATE ON public.users 
    FOR EACH ROW 
    EXECUTE FUNCTION public.update_user_timestamp();

DROP TRIGGER IF EXISTS set_timestamp ON public.notes;
CREATE TRIGGER set_timestamp 
    BEFORE UPDATE ON public.notes 
    FOR EACH ROW 
    EXECUTE FUNCTION public.update_timestamp();